
echo "NAME='int4_r1'     TYPE='integer'   KIND='(int_4)'   DIMENSION=', dimension(:)'             ZERO_SUB='iazzero_dont_use_me_anymore' "
echo "NAME='int4_r2'     TYPE='integer'   KIND='(int_4)'   DIMENSION=', dimension(:,:)'           ZERO_SUB='iazzero_dont_use_me_anymore' "
echo "NAME='int4_r3'     TYPE='integer'   KIND='(int_4)'   DIMENSION=', dimension(:,:,:)'         ZERO_SUB='iazzero_dont_use_me_anymore' "
echo "NAME='int4_r4'     TYPE='integer'   KIND='(int_4)'   DIMENSION=', dimension(:,:,:,:)'       ZERO_SUB='iazzero_dont_use_me_anymore' "
echo "NAME='int4_r5'     TYPE='integer'   KIND='(int_4)'   DIMENSION=', dimension(:,:,:,:,:)'     ZERO_SUB='iazzero_dont_use_me_anymore' "
echo "NAME='int4_r6'     TYPE='integer'   KIND='(int_4)'   DIMENSION=', dimension(:,:,:,:,:,:)'   ZERO_SUB='iazzero_dont_use_me_anymore' "
echo "NAME='int4_r7'     TYPE='integer'   KIND='(int_4)'   DIMENSION=', dimension(:,:,:,:,:,:,:)' ZERO_SUB='iazzero_dont_use_me_anymore' "

echo "NAME='int8_r1'     TYPE='integer'   KIND='(int_8)'   DIMENSION=', dimension(:)'             ZERO_SUB='i8azzero_dont_use_me_anymore' "
echo "NAME='int8_r2'     TYPE='integer'   KIND='(int_8)'   DIMENSION=', dimension(:,:)'           ZERO_SUB='i8azzero_dont_use_me_anymore' "
echo "NAME='int8_r3'     TYPE='integer'   KIND='(int_8)'   DIMENSION=', dimension(:,:,:)'         ZERO_SUB='i8azzero_dont_use_me_anymore' "
echo "NAME='int8_r4'     TYPE='integer'   KIND='(int_8)'   DIMENSION=', dimension(:,:,:,:)'       ZERO_SUB='i8azzero_dont_use_me_anymore' "
echo "NAME='int8_r5'     TYPE='integer'   KIND='(int_8)'   DIMENSION=', dimension(:,:,:,:,:)'     ZERO_SUB='i8azzero_dont_use_me_anymore' "
echo "NAME='int8_r6'     TYPE='integer'   KIND='(int_8)'   DIMENSION=', dimension(:,:,:,:,:,:)'   ZERO_SUB='i8azzero_dont_use_me_anymore' "
echo "NAME='int8_r7'     TYPE='integer'   KIND='(int_8)'   DIMENSION=', dimension(:,:,:,:,:,:,:)' ZERO_SUB='i8azzero_dont_use_me_anymore' "

echo "NAME='real8_r1'    TYPE='real'      KIND='(real_8)'  DIMENSION=', dimension(:)'             ZERO_SUB='azzero_dont_use_me_anymore' "
echo "NAME='real8_r2'    TYPE='real'      KIND='(real_8)'  DIMENSION=', dimension(:,:)'           ZERO_SUB='azzero_dont_use_me_anymore' "
echo "NAME='real8_r3'    TYPE='real'      KIND='(real_8)'  DIMENSION=', dimension(:,:,:)'         ZERO_SUB='azzero_dont_use_me_anymore' "
echo "NAME='real8_r4'    TYPE='real'      KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:)'       ZERO_SUB='azzero_dont_use_me_anymore' "
echo "NAME='real8_r5'    TYPE='real'      KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:,:)'     ZERO_SUB='azzero_dont_use_me_anymore' "
echo "NAME='real8_r6'    TYPE='real'      KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:,:,:)'   ZERO_SUB='azzero_dont_use_me_anymore' "
echo "NAME='real8_r7'    TYPE='real'      KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:,:,:,:)' ZERO_SUB='azzero_dont_use_me_anymore' "

echo "NAME='complex8_r1' TYPE='complex'   KIND='(real_8)'  DIMENSION=', dimension(:)'             ZERO_SUB='zazzero_dont_use_me_anymore' "
echo "NAME='complex8_r2' TYPE='complex'   KIND='(real_8)'  DIMENSION=', dimension(:,:)'           ZERO_SUB='zazzero_dont_use_me_anymore' "
echo "NAME='complex8_r3' TYPE='complex'   KIND='(real_8)'  DIMENSION=', dimension(:,:,:)'         ZERO_SUB='zazzero_dont_use_me_anymore' "
echo "NAME='complex8_r4' TYPE='complex'   KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:)'       ZERO_SUB='zazzero_dont_use_me_anymore' "
echo "NAME='complex8_r5' TYPE='complex'   KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:,:)'     ZERO_SUB='zazzero_dont_use_me_anymore' "
echo "NAME='complex8_r6' TYPE='complex'   KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:,:,:)'   ZERO_SUB='zazzero_dont_use_me_anymore' "
echo "NAME='complex8_r7' TYPE='complex'   KIND='(real_8)'  DIMENSION=', dimension(:,:,:,:,:,:,:)' ZERO_SUB='zazzero_dont_use_me_anymore' "
