C $Id: pmdblock.h,v 1.1 2006-12-27 11:29:29 itavern Exp $
C

C     THIS FILE DEFINES CONSTANTS AND TABLES
C     FOR READING PRE MD PROGRAM-STYLE FILES IN THE GROMOS FORMAT.

C     DEFINE THE LEGAL BLOCK TYPES HERE
      INTEGER NEND, NTITL, NCS1, NCS2, NGCA, NGCH, NSSC,
     $        NBOX, NGMT, NGWH, NCRY, NION, NMMT, NCMT, NPMT, NGCB

      PARAMETER ( NEND =   1)
      PARAMETER ( NTITL =  2)
      PARAMETER ( NGMT =   3)
      PARAMETER ( NMMT =   4)
      PARAMETER ( NCMT =   5)
      PARAMETER ( NPMT =   6) 
      PARAMETER ( NCS1 =   7)
      PARAMETER ( NCS2 =   8)
      PARAMETER ( NGCB =   9) 
      PARAMETER ( NGCA =  10)
      PARAMETER ( NSSC =  11)
      PARAMETER ( NGCH =  12)
      PARAMETER ( NGWH =  13)
      PARAMETER ( NCRY =  14)
      PARAMETER ( NBOX =  15)
      PARAMETER ( NION =  16)

C
C     ADD OTHER BLOCK TYPES HERE.
C     REMEMBER TO CHANGE MAXBT IN ACCORDANCE!

      INTEGER MINBT, MAXBT,NBTERR
      PARAMETER (NBTERR = 0, MINBT = NEND, MAXBT = NION)


C     MAXIMUM LENGTH OF BLOCK TYPE NAMES
      INTEGER MXBTLE
      PARAMETER (MXBTLE = 16)

      LOGICAL LGOT
      COMMON /NBTGOT/ LGOT(MAXBT)

      CHARACTER* (MXBTLE) BTNAME
      COMMON /NBTCH/ BTNAME(MAXBT)


C     THE ARRAY BTNAME IS INITIALIZED IN THE
C     BLOCKDATA STATEMENT IN RDMD.F
C     THE ARRAY LGOT IS INITIALIZED BY SUBR. RDPMD AT RUNTIME.


C SOME STRINGS USED AS FORMAT STATEMENTS FOR WRITING OUT ERRORS
C THESE STRINGS ARE INITIALIZED IN A BLOCKDATA STATEMENT IN RDMD.F

      CHARACTER*(40) FMNII
      CHARACTER*(40) FMNIR
      CHARACTER*(32) FMGEI
      CHARACTER*(32) FMGER
      CHARACTER*(32) FMGTI
      CHARACTER*(32) FMGTR
      CHARACTER*(40) FMBTI
      CHARACTER*(44) FMBTR

      COMMON /MDFMST/FMNII,FMNIR,FMGEI,FMGER,FMGTI,FMGTR,FMBTI,FMBTR
