C  $Id: vector.h,v 1.1 2006-12-27 11:36:05 itavern Exp $
C

C     INCLUDE forcesz.h AND coordsz.h BEFORE THIS ONE
C
      INTEGER MAXP, MFORCE, MAXANG,
     $        JRCNPC, JRCNJA, IVECT,
     $        MAXGRP, IEPAIR, MAXGP

      PARAMETER (MAXP = 3001, MFORCE = 10001, MAXANG = 2001,
     $        JRCNPC = 5*MAXP, JRCNJA = 9, IVECT = 64,
     $        MAXGRP = 8, IEPAIR = MAXGRP * (MAXGRP + 1) / 2,
     $        MAXGP = 4001)


      LOGICAL LBVIR, LLPERT, LLPERJ, LNEWP

      INTEGER INAG, IFIRST, INTROW, JRCIND,
     $        ICET, NSPTT, ISCLJT, ISCCT, ISCLJJ, ISCCJ,
     $        IACT, IACBT, IACAJ, IACBJ, JLIST, JRCILJ,
     $        JRCPAC, JFIRST, JRCBK1,
     $        JRCBK2, IPICJ, IPICT,
     $        NJL, NSPJ, IOCVIR, NILIST, JFORCE,
     $        IFORCE

      REAL XC, YC, ZC, WC,
     $     XRC, YRC, ZRC,
     $     XDST, YDST, ZDST,
     $     XJ , YJ , ZJ, WJ,
     $     VXIJ, VYIJ, VZIJ, VWIJ,  
     $     FLRX, FLRY, FLRZ, FLRW,
     $     FXTEMP, FYTEMP, FZTEMP, FWTEMP,
     $     CGAT, CGBT, CGAJ, CGBJ, FC12C6, AC12C6, BC12C6,
     $     FORC6, FORC12, VC6A, VC12A, VC6B, VC12B, VXH, VYH, VZH, VWH,
     $     R2D, XRJ, YRJ, ZRJ, VRIJ, VRINV, VRINV2, VRINV6, R2IJ3D,
     $     VEELJ, VERFJ, VERCJ, VLJJ, DFRF, VRIJ2, TVIR, 
     $     TEEL, TERF, TERC, TELJ, DF3, PIFACT, DF4TH,
     $     EGLELJ, EGLRFJ, EGLRCJ, EGLLJJ,
     $     AMULT, BMULT, E34ELJ, E34RFJ, E34RCJ, E34LJJ
     

      COMMON /LVECT/ LBVIR(MAXNAT), LLPERT(MAXNAT), LLPERJ(MAXP),
     $     LNEWP

      COMMON /KVECT/ INAG(MAXINB), IFIRST(MAXINB), 
     $     ICET(MAXNAT), NSPTT(MAXNAT), ISCLJT(MAXNAT),
     $     ISCCT(MAXNAT), ISCLJJ(MAXP), ISCCJ(MAXP), INTROW(MAXINB), 
     $     JRCIND(MAXINB), IACT(MAXNAT), IACBT(MAXNAT), IACBJ(MAXP),
     $     IACAJ(MAXP), JLIST(MAXNAT), NILIST(MAXP),
     $     JRCPAC(JRCNPC), JFIRST(MAXINB), JRCILJ(MAXNAT),
     $     JRCBK1(MAXP),JRCBK2(MAXP), IPICJ(MAXP), 
     $     IPICT(MAXNAT), NJL(MAXINB), NSPJ(MAXP),
     $     IOCVIR(MAXNAT), IFORCE(MAXP), JFORCE(MAXGP)

      COMMON /RVECT/ XC(MAXNAT), YC(MAXNAT), ZC(MAXNAT), WC(MAXNAT),
     $     XRC(MAXNAT), YRC(MAXNAT), ZRC(MAXNAT), DF4TH(MAXP),
     $     XDST(MAXINB), YDST(MAXINB), ZDST(MAXINB), 
     $     XJ(MAXNAT), YJ(MAXNAT), ZJ(MAXNAT), WJ(MAXNAT),
     $     VXIJ(MAXINB), VYIJ(MAXINB), VZIJ(MAXINB), VWIJ(MAXINB),
     $     FLRX(MAXNAT), FLRY(MAXNAT), FLRZ(MAXNAT), FLRW(MAXNAT),
     $     FXTEMP(MAXP), FYTEMP(MAXP), FZTEMP(MAXP), FWTEMP(MAXP), 
     $     CGAT(MAXNAT), CGBT(MAXNAT), CGAJ(MAXP), CGBJ(MAXP),
     $     FORC6(MFORCE), FORC12(MFORCE), VC6A(MAXP), VC12A(MAXP), 
     $     VC6B(MAXP), VC12B(MAXP), FC12C6(MFORCE), AC12C6(MAXP), 
     $     VXH(MAXP), VYH(MAXP), VZH(MAXP), VWH(MAXP),
     $     BC12C6(MAXP), R2IJ3D(MAXP),
     $     R2D(MAXINB), XRJ(MAXINB), YRJ(MAXINB), ZRJ(MAXINB), 
     $     VRIJ(MAXP), VRINV(MAXP), VRINV2(MAXP), VRINV6(MAXP),
     $     VEELJ(MAXINB), VERFJ(MAXP), VERCJ(MAXP), VLJJ(MAXP),
     $     DFRF(MAXP), VRIJ2(MAXINB), TVIR(MAXP, 3), 
     $     TEEL(IEPAIR, IVECT), TERF(IEPAIR, IVECT), PIFACT(MAXP),
     $     TERC(IEPAIR, IVECT), TELJ(IEPAIR, IVECT), DF3(MAXP),
     $     EGLELJ(MAXP), EGLRFJ(MAXP), EGLRCJ(MAXP), 
     $     EGLLJJ(MAXP), AMULT(MAXGP), BMULT(MAXGP), 
     $     E34ELJ(MAXP), E34RFJ(MAXP), E34RCJ(MAXP), E34LJJ(MAXP)


