MODULE kinds

  IMPLICIT NONE

  PRIVATE

  INTEGER, PARAMETER, PUBLIC :: real_4 = SELECTED_REAL_KIND ( 6, 30 )
  INTEGER, PARAMETER, PUBLIC :: real_8 = SELECTED_REAL_KIND ( 14, 200 )

  INTEGER, PARAMETER, PUBLIC :: int_1 = SELECTED_INT_KIND(2)
  INTEGER, PARAMETER, PUBLIC :: int_2 = SELECTED_INT_KIND(4)
  INTEGER, PARAMETER, PUBLIC :: int_4 = SELECTED_INT_KIND(5)
  INTEGER, PARAMETER, PUBLIC :: int_8 = SELECTED_INT_KIND(10)

  INTEGER, PARAMETER, PUBLIC :: default_string_length = 80
  INTEGER, PARAMETER, PUBLIC :: long_string_length = 10*default_string_length
  INTEGER, PARAMETER, PUBLIC :: default_path_length = 512

END MODULE kinds
