subroutine zeroing_int4_r1(data)
  ! Arguments
  integer(int_4), intent(inout) , dimension(:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int4_r1'
  if(size(data)>0) then
     call iazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int4_r1
subroutine zeroing_int4_r2(data)
  ! Arguments
  integer(int_4), intent(inout) , dimension(:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int4_r2'
  if(size(data)>0) then
     call iazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int4_r2
subroutine zeroing_int4_r3(data)
  ! Arguments
  integer(int_4), intent(inout) , dimension(:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int4_r3'
  if(size(data)>0) then
     call iazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int4_r3
subroutine zeroing_int4_r4(data)
  ! Arguments
  integer(int_4), intent(inout) , dimension(:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int4_r4'
  if(size(data)>0) then
     call iazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int4_r4
subroutine zeroing_int4_r5(data)
  ! Arguments
  integer(int_4), intent(inout) , dimension(:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int4_r5'
  if(size(data)>0) then
     call iazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int4_r5
subroutine zeroing_int4_r6(data)
  ! Arguments
  integer(int_4), intent(inout) , dimension(:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int4_r6'
  if(size(data)>0) then
     call iazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int4_r6
subroutine zeroing_int4_r7(data)
  ! Arguments
  integer(int_4), intent(inout) , dimension(:,:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int4_r7'
  if(size(data)>0) then
     call iazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int4_r7
subroutine zeroing_int8_r1(data)
  ! Arguments
  integer(int_8), intent(inout) , dimension(:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int8_r1'
  if(size(data)>0) then
     call i8azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int8_r1
subroutine zeroing_int8_r2(data)
  ! Arguments
  integer(int_8), intent(inout) , dimension(:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int8_r2'
  if(size(data)>0) then
     call i8azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int8_r2
subroutine zeroing_int8_r3(data)
  ! Arguments
  integer(int_8), intent(inout) , dimension(:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int8_r3'
  if(size(data)>0) then
     call i8azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int8_r3
subroutine zeroing_int8_r4(data)
  ! Arguments
  integer(int_8), intent(inout) , dimension(:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int8_r4'
  if(size(data)>0) then
     call i8azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int8_r4
subroutine zeroing_int8_r5(data)
  ! Arguments
  integer(int_8), intent(inout) , dimension(:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int8_r5'
  if(size(data)>0) then
     call i8azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int8_r5
subroutine zeroing_int8_r6(data)
  ! Arguments
  integer(int_8), intent(inout) , dimension(:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int8_r6'
  if(size(data)>0) then
     call i8azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int8_r6
subroutine zeroing_int8_r7(data)
  ! Arguments
  integer(int_8), intent(inout) , dimension(:,:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_int8_r7'
  if(size(data)>0) then
     call i8azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_int8_r7
subroutine zeroing_real8_r1(data)
  ! Arguments
  real(real_8), intent(inout) , dimension(:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_real8_r1'
  if(size(data)>0) then
     call azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_real8_r1
subroutine zeroing_real8_r2(data)
  ! Arguments
  real(real_8), intent(inout) , dimension(:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_real8_r2'
  if(size(data)>0) then
     call azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_real8_r2
subroutine zeroing_real8_r3(data)
  ! Arguments
  real(real_8), intent(inout) , dimension(:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_real8_r3'
  if(size(data)>0) then
     call azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_real8_r3
subroutine zeroing_real8_r4(data)
  ! Arguments
  real(real_8), intent(inout) , dimension(:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_real8_r4'
  if(size(data)>0) then
     call azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_real8_r4
subroutine zeroing_real8_r5(data)
  ! Arguments
  real(real_8), intent(inout) , dimension(:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_real8_r5'
  if(size(data)>0) then
     call azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_real8_r5
subroutine zeroing_real8_r6(data)
  ! Arguments
  real(real_8), intent(inout) , dimension(:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_real8_r6'
  if(size(data)>0) then
     call azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_real8_r6
subroutine zeroing_real8_r7(data)
  ! Arguments
  real(real_8), intent(inout) , dimension(:,:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_real8_r7'
  if(size(data)>0) then
     call azzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_real8_r7
subroutine zeroing_complex8_r1(data)
  ! Arguments
  complex(real_8), intent(inout) , dimension(:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_complex8_r1'
  if(size(data)>0) then
     call zazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_complex8_r1
subroutine zeroing_complex8_r2(data)
  ! Arguments
  complex(real_8), intent(inout) , dimension(:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_complex8_r2'
  if(size(data)>0) then
     call zazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_complex8_r2
subroutine zeroing_complex8_r3(data)
  ! Arguments
  complex(real_8), intent(inout) , dimension(:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_complex8_r3'
  if(size(data)>0) then
     call zazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_complex8_r3
subroutine zeroing_complex8_r4(data)
  ! Arguments
  complex(real_8), intent(inout) , dimension(:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_complex8_r4'
  if(size(data)>0) then
     call zazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_complex8_r4
subroutine zeroing_complex8_r5(data)
  ! Arguments
  complex(real_8), intent(inout) , dimension(:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_complex8_r5'
  if(size(data)>0) then
     call zazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_complex8_r5
subroutine zeroing_complex8_r6(data)
  ! Arguments
  complex(real_8), intent(inout) , dimension(:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_complex8_r6'
  if(size(data)>0) then
     call zazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_complex8_r6
subroutine zeroing_complex8_r7(data)
  ! Arguments
  complex(real_8), intent(inout) , dimension(:,:,:,:,:,:,:) :: data
  ! Variables
  character(*),parameter :: procedureN='zeroing_complex8_r7'
  if(size(data)>0) then
     call zazzero_dont_use_me_anymore(data,size(data))
  endif
end subroutine zeroing_complex8_r7
